//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public narudzbe()
        {
            this.proizvodi_na_narudzbi = new HashSet<proizvodi_na_narudzbi>();
            this.racuni = new HashSet<racuni>();
        }
    
        public int narudzba_ID { get; set; }
        public byte[] datum_stvaranja { get; set; }
        public System.DateTime datum_isporuke { get; set; }
        public string status { get; set; }
        public int kupac_ID { get; set; }
    
        public virtual kupci kupci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proizvodi_na_narudzbi> proizvodi_na_narudzbi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racuni> racuni { get; set; }
    }
}
