//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proizvodi()
        {
            this.proizvodi_na_narudzbi = new HashSet<proizvodi_na_narudzbi>();
        }
    
        public int proizvod_ID { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public double cijena { get; set; }
        public int raspolozivo { get; set; }
        public int mjerna_jedinica_ID { get; set; }
    
        public virtual mjerne_jedinice mjerne_jedinice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proizvodi_na_narudzbi> proizvodi_na_narudzbi { get; set; }
    }
}
