//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvodi_na_narudzbi
    {
        public int proizvod_ID { get; set; }
        public int narudzba_ID { get; set; }
        public int kolicina { get; set; }
    
        public virtual narudzbe narudzbe { get; set; }
        public virtual proizvodi proizvodi { get; set; }
    }
}
